Itldetailing/Models/Supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itldetailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Product_Order = new HashSet<Product_Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AcCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public string Location { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> EnableFalg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order> Product_Order { get; set; }
    }
}

Itldetailing/Controllers/SupplierController.cs
using Itldetailing.Models;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Itldetailing.Controllers
{
    public class SupplierController : BaseController
    {
        SafdarElectronicsEntities db = new SafdarElectronicsEntities();
        // GET: Supplier
        public ActionResult Index()
        {
            ViewBag.S = db.Suppliers.Where(x => x.EnableFalg == true).ToList();
            return View();
        }
        public ActionResult Save(Supplier model)
        {
            if (model != null)
            {
                try
                {
                    model.EnableFalg = true;
                    //model.CreatedBy = GetUser();
                    model.CreatedDate = DateTime.UtcNow.AddHours(5);
                    db.Suppliers.Add(model);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return RedirectToAction("index");
        }

        private object GetUser()
        {
            throw new NotImplementedException();
        }

        public JsonResult delete(int id)
        {
            string res = "";
            try
            {
                var model = db.Suppliers.Find(id);
                model.EnableFalg = false;

                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();

                res = "true";
            }
            catch (Exception ex)
            {
                res = "false";
            }
            return Json(res);
        }
        public ActionResult Partial()
        {
            {
                var model = db.Suppliers.Where(x => x.EnableFalg == true).ToList();

                if (model == null)
                {
                    model = new List<Supplier>();
                }

                return PartialView("~/Views/Supplier/SupplierPartial.cshtml", model);
            }
            
        }
        public ActionResult Edit(int id)
        {
            ViewBag.M = db.Suppliers.Where(x => x.EnableFalg == true).ToList();

            var model = db.Suppliers.Find(id);
            return View(model);
        }
    }
    
}

Itldetailing/Views/Supplier/Edit.cshtml
@model Itldetailing.Models.Supplier

<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h3 class="mainTitle">Supplier Information</h3>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Home</span>
            </li>
            <li class="active">
                <span> Add Supplier Information</span>
            </li>
        </ol>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div id="" class="row">
        <hr />
        @using (Html.BeginForm("Save", "Supplier", FormMethod.Post, new { encType = "multipart/form-data", id = "form" }))
        {
            ///////////////////CSTMR//////////////////////////
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CreatedBy)
            @Html.HiddenFor(x => x.CreatedDate)
            @Html.ValidationSummary()
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Code.# <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.AcCode, new { @class = "form-control" })
                    </div>

                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Description <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Location <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Credit Amount <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.CreditAmount, new { @class = "form-control" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Debit Amount <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.DebitAmount, new { @class = "form-control" })
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary btn-wide pull-right" style="margin-right:200px;" type="submit">
                        Update <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </div>
        }
    </div>
</div>

@*<input type="hidden" id="hidPartialViewUrl" value="@Url.Action("Partial", "Supplier")" />*@

@*@section Scripts {
    <script src="~/Content/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="~/Content/vendor/autosize/autosize.min.js"></script>
    <script src="~/Content/vendor/selectFx/classie.js"></script>
    <script src="~/Content/vendor/selectFx/selectFx.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script src="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/assets/js/form-elements.js"></script>
    
}

@section CSS {
    <link href="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
}*@

Itldetailing/Views/Supplier/Index.cshtml
@model Itldetailing.Models.Supplier

<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h3 class="mainTitle">Supplier Information</h3>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Home</span>
            </li>
            <li class="active">
                <span> Add Supplier Information</span>
            </li>
        </ol>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="row" id="divAdd">
        <div class="col-sm-12">
            <button class="btn btn-success" style="margin-left: 15px;" onclick="showAdd('show')"><i class="fa fa-plus"></i>Add Supplier</button>
        </div>
    </div>
    <div class="row" style="display: none" id="divClose">
        <div class="col-sm-12">
            <button class="btn btn-danger" style="margin-left: 15px;" onclick="showAdd('hide')"><b><i class="fa fa-minus"></i>Close</b></button>
        </div>
    </div>
    <div id="divHide" class="row">
        <hr />
        @using (Html.BeginForm("Save", "Supplier", FormMethod.Post, new { encType = "multipart/form-data", id = "form" }))
        {
            ///////////////////CSTMR//////////////////////////
            @*@Html.HiddenFor(x => x.cstmr.Id)*@
            @Html.ValidationSummary()
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Code.# <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.AcCode, new { @class = "form-control",placeholder="Supplier Code.#" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Description <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Description, new { @class = "form-control", placeholder = "Supplier Description" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Supplier Location <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Location, new { @class = "form-control", placeholder = "Supplier Location" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Credit Amount <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.CreditAmount, new { @class = "form-control", placeholder = "Supplier Credit" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Debit Amount <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.DebitAmount, new { @class = "form-control", placeholder = "Supplier Debit" })
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary btn-wide pull-right" style="margin-right:200px;" type="submit">
                        Save <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </div>
        }
    </div>
</div>
<div class="container-fluid container-fullw bg-white">
    <div id="divPartialView" class="row">

    </div>
</div>

<input type="hidden" id="hidPartialViewUrl" value="@Url.Action("Partial", "Supplier")" />

@section Scripts {
    <script src="~/Content/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="~/Content/vendor/autosize/autosize.min.js"></script>
    <script src="~/Content/vendor/selectFx/classie.js"></script>
    <script src="~/Content/vendor/selectFx/selectFx.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script src="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/assets/js/form-elements.js"></script>
    <script>
        jQuery(document).ready(function () {
            FormElements.init();
            validation();
        });
        function getConfirmation(id) {
            var ID = id;
            var retVal = confirm("Sure You Wana Delete it?");
            if (retVal == true) {
                var getUrl = "/Supplier/delete"; // Controller Action Url (Delete function)
                $.ajax({
                    url: getUrl,
                    type: "POST",
                    data: { id: ID },
                    success: function (res) {
                        loadPartialView();
                        return true;
                    },
                });
            }
            
            
            else {
                return false;
            }
        }

    </script>
}

@section CSS {
    <link href="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
}

Itldetailing/Views/Supplier/SupplierPartial.cshtml
@model  List<Itldetailing.Models.Supplier>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="sample-table-1">
        <thead>
            <tr>
                <th>No.</th>
                <th>Description</th>
                <th>Location</th>
                <th>Credit</th>
                <th>Debit</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {

                    <tr>
                        <td> @i</td>
                        <td> @item.Description</td>
                        <td> @item.Location</td>
                        <td> @item.CreditAmount</td>
                        <td> @item.DebitAmount</td>
                        <td class="text-center">
                            <a class="label label-danger" onclick="getConfirmation(@item.Id);"><i class="fa fa-times"></i></a>
                            <a class="label label-default" href="@Url.Action("Edit", "Supplier", new { id = item.Id })"><i class="fa fa-pencil"></i></a>
                        </td>
                    </tr>
                        i++;
                    }
                }

        </tbody>
    </table>
</div>