Itldetailing/Models/AddCostmorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Itldetailing.Models
{
    public class AddCostmorViewModel
    {
        //public CostomorInfo cstmr { get; set; }
        //public Varification varification { get; set; }
        //public Witness witness { get; set; }
    }
}

Itldetailing/Controllers/AddCostmorController.cs
using Itldetailing.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Itldetailing.Controllers
{
    public class AddCostmorController : BaseController
    {
        //SafdarElectronicsEntities db = new SafdarElectronicsEntities();
        //// GET: TestimonalsForm
        //public ActionResult Index()
        //{
        //    return View(new AddCostmorViewModel());
        //}

        //public ActionResult View()
        //{
        //    return PartialView("~/Views/AddCostmor/_AddPartial.cshtml", db.CostomorInfoes.ToList());
        //}

        //public ActionResult Save(AddCostmorViewModel model)
        //{
        //    if (model != null)
        //    { 
        //        db.Entry(model.cstmr).State = model.cstmr.Id == 0 ? EntityState.Added : EntityState.Modified;
        //        db.SaveChanges();

        //        model.witness.FKCostmerId = model.cstmr.Id;
        //        db.Entry(model.witness).State = model.witness.Id == 0 ? EntityState.Added : EntityState.Modified;

        //        db.SaveChanges();
        //    }
        //    return RedirectToAction("index");
        //}

        //public ActionResult Edit(int id)
        //{
        //    var model = db.CostomorInfoes.FirstOrDefault(x => x.Id == id);

        //    return View(model);
        //}

        //public ActionResult delete(int id)
        //{
        //    try
        //    {
        //        db.Witnesses.Remove(db.Witnesses.FirstOrDefault(x=>x.FKCostmerId == id));
        //        db.SaveChanges();

        //        db.CostomorInfoes.Remove(db.CostomorInfoes.Find(id));
        //        db.SaveChanges();
        //    }
        //    catch (Exception ex)
        //    {

        //    }

        //    return RedirectToAction("index");
        //}
    }
}

Itldetailing/Views/AddCostmor/_AddPartial.cshtml
@model  List<Itldetailing.Models.CostomorInfo>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="sample-table-1">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Cnic</th>
                <th>Customer Type</th>
                <th>Mobile number</th>
                <th>Profession</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {

                    <tr>
                        <td> @i</td>
                        <td> @(item.Name + " " + item.FatherName)</td>
                        <td> @item.CNIC</td>
                        <td> @item.TypeCostmor</td>
                        <td> @item.MobileNumber</td>
                        <td> @item.Profession</td>
                        <td class="text-center">
                            <a class="label label-danger" onclick="getConfirmation(@item.Id);"><i class="fa fa-times"></i></a>
                            <a class="label label-default" href="@Url.Action("Edit", "AddCostmor", new { id = item.Id })"><i class="fa fa-user"></i></a>
                        </td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>