Itldetailing/Controllers/ManageRolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Itldetailing.Models;

namespace Itldetailing.Controllers
{
    public class ManageRolesController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Roles()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            ViewBag.roles = roleManager.Roles.ToList();
            return View();
        }

        public ActionResult RolesView()
        {

            ApplicationDbContext context = new ApplicationDbContext();
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            var roles = roleManager.Roles.ToList();
            return PartialView("~/Views/ManageRoles/_RolesView.cshtml", roles);
        }

        public string SaveRole(string nameParam)
        {
            string res = "false";

            ApplicationDbContext context = new ApplicationDbContext();
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));

            if (!roleManager.RoleExists(nameParam))
            {
                var role = new IdentityRole();
                role.Name = nameParam;
                roleManager.Create(role);
                return "true";
            }
            else
            {
                return res;
            }
        }

        public void deleteRole(string nameParam)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));

            if (roleManager.RoleExists(nameParam))
            {
                var role = roleManager.FindByName(nameParam);
                roleManager.Delete(role);
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

Itldetailing/Views/ManageRoles/Roles.cshtml
@{
    ViewBag.Title = "Roles";
}
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h3 class="mainTitle">Roles</h3>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Home</span>
            </li>
            <li class="active">
                <span>Add Roles</span>
            </li>
        </ol>
    </div>
</section>

<div class="container-fluid container-fullw bg-white">
    <div class="row" id="divAdd">
        <div class="col-sm-12">
            <button class="btn btn-success" style="margin-left: 15px;" onclick="showAdd('show')"><i class="fa fa-plus"></i>Add Role</button>
        </div>
    </div>
    <div class="row" style="display: none" id="divClose">
        <div class="col-sm-12">
            <button class="btn btn-danger" style="margin-left: 15px;" onclick="showAdd('hide')"><b><i class="fa fa-minus"></i>Close</b></button>
        </div>
    </div>
    <div id="divHide" class="row">
        <hr />
        <div class="col-sm-8">
            <div class="input-group">
                <div class="col-sm-10">
                    <input id="role" type="text" placeholder="Add Roles" class="form-control">
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-success" onclick="save()" id="Submite">Add Role</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid container-fullw bg-white">
    <div id="divPartialView" class="row">

    </div>
</div>

<input type="hidden" id="hidPartialViewUrl" value="@Url.Action("RolesView", "ManageRoles")" />
<input type="hidden" id="hidSaveRoleUrl" value="@Url.Action("SaveRole", "ManageRoles")" />
<input type="hidden" id="hidDeleteRoleUrl" value="@Url.Action("deleteRole", "ManageRoles")" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Itldetailing/Views/ManageRoles/_RolesView.cshtml
@model  IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="sample-table-1">
        <thead>
            <tr>
                <th>No.</th>
                <th>Roles</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @{
                    int i = 1;
                    foreach (var item in Model)
                    {

                    <tr>
                        <td>@i</td>
                        <td>@(item.Name == null ? "" : item.Name)</td>
                        <td class="text-center">
                            <a class="label label-danger" onclick="deleteRole('@item.Name')"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>