Itldetailing/Models/Employe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itldetailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.Customer_Verification = new HashSet<Customer_Verification>();
        }
    
        public int id { get; set; }
        public string EmployeStatus { get; set; }
        public string EmployeName { get; set; }
        public Nullable<int> Employecode { get; set; }
        public string EmployeFather { get; set; }
        public string EmployeDesignation { get; set; }
        public string EmployeAddress { get; set; }
        public string EmployeMobile { get; set; }
        public string EmployeCnic { get; set; }
        public Nullable<int> EmployeSalary { get; set; }
        public Nullable<int> AdvanceSalary { get; set; }
        public Nullable<bool> EnableFalg { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Verification> Customer_Verification { get; set; }
    }
}

Itldetailing/Controllers/EmployeController.cs
using Itldetailing.Models;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Itldetailing.Controllers 
{
    
    public class EmployeController : BaseController
    {
        SafdarElectronicsEntities db = new SafdarElectronicsEntities();
        // GET: Employe
        public ActionResult Index()
        {
            ViewBag.E = db.Employes.Where(x => x.EnableFalg == true).ToList();
            return View(new Employe());
        }
        public ActionResult Save(Employe model)
        {
            if (model != null)
            {
                try
                {
                    model.EnableFalg = true;
                    model.CreatedBy = GetUser().UserName;
                    model.CreatedDate = DateTime.UtcNow.AddHours(5);
                    db.Employes.Add(model);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return RedirectToAction("index");
        }
        public JsonResult delete(int id)
        {
            string res = "";
            try
            {
                var model = db.Employes.Find(id);
                model.EnableFalg = false;

                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();

                res = "true";
            }
            catch (Exception ex)
            {
                res = "false";
            }
            return Json(res);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.M = db.Employes.Where(x => x.EnableFalg == true).ToList();

            var model = db.Employes.Find(id);
            return View(model);
        }
        public ActionResult Partial()
        {
            var model = db.Employes.Where(x => x.EnableFalg == true).ToList();

            if (model == null)
            {
                model = new List<Employe>();
            }

            return PartialView("~/Views/Employe/EmployePartial.cshtml",model);
        }
    }
}

Itldetailing/Views/Employe/Edit.cshtml
@model Itldetailing.Models.Employe

<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h3 class="mainTitle">Employe Information</h3>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Home</span>
            </li>
            <li class="active">
                <span> Add Employe Information</span>
            </li>
        </ol>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div id="" class="row">
        <hr />
        @using (Html.BeginForm("Save", "Employe", FormMethod.Post, new { encType = "multipart/form-data", id = "form" }))
        {
            /////////////////////CSTMR//////////////////////////
            @Html.HiddenFor(x => x.id)
            @Html.HiddenFor(x => x.CreatedBy)
            @Html.HiddenFor(x=>x.CreatedDate)
            @Html.ValidationSummary()
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Code.# <span class="symbol" aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Employecode, new { @class = "form-control", placeholder = "Employe Code.#" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Name <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeName, new { @class = "form-control", placeholder = "Employe Name" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Father Name <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeFather, new { @class = "form-control", placeholder = "Employe Father Name" })
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Mobile Number <span class="symbol" aria="false"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeMobile, new { @class = "form-control", placeholder = "Employe Mobile" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe CNIC <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeCnic, new { @class = "form-control", placeholder = "Employe CNIC" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Address <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeAddress, new { @class = "form-control", placeholder = "Employe Address" })
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Designation <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeDesignation, new { @class = "form-control", placeholder = "Employe Designation" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Salary <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeSalary, new { @class = "form-control", placeholder = "Employe Salary" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Advance Salary <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.AdvanceSalary, new { @class = "form-control", placeholder = "Employe Advance Salary" })
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary btn-wide pull-right" style="margin-right:200px;" type="submit">
                        Update <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </div>
        }
    </div>
</div>

@*<input type="hidden" id="hidPartialViewUrl" value="@Url.Action("Partial", "Employe")" />*@
@*<input type="hidden" id="hidDeleteRoleUrl" value="@Url.Action("delete", "Employe")" />*@


@*@section Scripts {
    <script src="~/Content/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="~/Content/vendor/autosize/autosize.min.js"></script>
    <script src="~/Content/vendor/selectFx/classie.js"></script>
    <script src="~/Content/vendor/selectFx/selectFx.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script src="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/assets/js/form-elements.js"></script>
    
}

@section CSS {
    <link href="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">*@
}

Itldetailing/Views/Employe/EmployePartial.cshtml
@model  List<Itldetailing.Models.Employe>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="sample-table-1">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Cnic</th>                
                <th>Mobile number</th>
                <th>Designation</th>
                <th>Salary</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {

                    <tr>
                        <td> @i</td>
                        <td> @(item.EmployeName + " " + item.EmployeFather)</td>
                        <td> @item.EmployeCnic</td>
                        <td> @item.EmployeMobile</td>
                        <td> @item.EmployeDesignation</td>
                        <td> @item.EmployeSalary</td>
                        <td class="text-center">
                            <a class="label label-danger" onclick="getConfirmation(@item.id);"><i class="fa fa-times"></i></a>
                            <a class="label label-default" href="@Url.Action("Edit", "Employe", new { id = item.id })"><i class="fa fa-pencil"></i></a>
                        </td>
                    </tr>
                        i++;
                    } 
                }
        </tbody>
    </table>
</div>

Itldetailing/Views/Employe/Index.cshtml
@model Itldetailing.Models.Employe

<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h3 class="mainTitle">Employe Information</h3>
        </div>
        <ol class="breadcrumb">
            <li>
                <span>Home</span>
            </li>
            <li class="active">
                <span> Add Employe Information</span>
            </li>
        </ol>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="row" id="divAdd">
        <div class="col-sm-12">
            <button class="btn btn-success" style="margin-left: 15px;" onclick="showAdd('show')"><i class="fa fa-plus"></i>Add Employe</button>
        </div>
    </div>
    <div class="row" style="display: none" id="divClose">
        <div class="col-sm-12">
            <button class="btn btn-danger" style="margin-left: 15px;" onclick="showAdd('hide')"><b><i class="fa fa-minus"></i>Close</b></button>
        </div>
    </div>
    <div id="divHide" class="row">
        <hr />
        @using(Html.BeginForm("Save", "Employe", FormMethod.Post, new { encType = "multipart/form-data", id = "form" }))
        {
            /////////////////////CSTMR//////////////////////////
            @Html.HiddenFor(x => x.id)
            @Html.HiddenFor(x=>x.CreatedBy)
            @Html.HiddenFor(x=>x.CreatedDate)
            @Html.ValidationSummary()
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Code.# <span class="symbol" aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.Employecode, new { @class= "form-control", placeholder = "Employe Code.#" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Name <span class="symbol " aria="true"></span>
                        </label>
                       @Html.TextBoxFor(x => x.EmployeName, new { @class = "form-control", placeholder = "Employe Name" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Father Name <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeFather, new { @class = "form-control", placeholder = "Employe Father Name" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Mobile Number <span class="symbol" aria="false"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeMobile, new { @class = "form-control", placeholder = "Employe Mobile" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe CNIC <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeCnic, new { @class = "form-control", placeholder = "Employe CNIC" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Address <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeAddress, new { @class = "form-control", placeholder = "Employe Address" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Designation <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeDesignation, new { @class = "form-control", placeholder = "Employe Designation" })
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Salary <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.EmployeSalary, new { @class = "form-control", placeholder = "Employe Salary" })
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 col-md-offset-1 col-lg-offset-1 col-sm-offset-1 col-xs-offset-1">
                    <div class="form-group">
                        <label class="control-label">
                            Employe Advance Salary <span class="symbol " aria="true"></span>
                        </label>
                        @Html.TextBoxFor(x => x.AdvanceSalary, new { @class = "form-control", placeholder = "Employe Advance Salary" })
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary btn-wide pull-right" style="margin-right:200px;" type="submit">
                        Save <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </div>
        }
    </div>
</div>
<div class="container-fluid container-fullw bg-white">
    <div id="divPartialView" class="row">

    </div>
</div>

<input type="hidden" id="hidPartialViewUrl" value="@Url.Action("Partial", "Employe")" />
<input type="hidden" id="hidDeleteRoleUrl" value="@Url.Action("delete", "Employe")" />


@section Scripts {
    <script src="~/Content/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="~/Content/vendor/autosize/autosize.min.js"></script>
    <script src="~/Content/vendor/selectFx/classie.js"></script>
    <script src="~/Content/vendor/selectFx/selectFx.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script src="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/assets/js/form-elements.js"></script>
    <script>
        jQuery(document).ready(function () {
            FormElements.init();
            validation();
        });
        function getConfirmation(id) {
            var ID = id;
            var retVal = confirm("Sure You Wana Delete it?");
            if (retVal == true) {
                var getUrl = "/Employe/delete"; // Controller Action Url (Delete function)
                $.ajax({
                    url: getUrl,
                    type: "POST",
                    data: { id: ID },
                    success: function (res) {
                        loadPartialView();
                        return true;
                    },
                });
            }
            else {
                return false;
            }
        }

</script>
}

@section CSS {
    <link href="~/Content/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
}